### ISSUE TITLE
Отсутствие файла в репозитории

### ISSUE THREAD

**Issue by Mejoove** [DedLovesFrogs/Simple-jewelery-DB-app-RU-#1]
У вас в проекте отсутствует файл Auth.Designer.cs 
Прошу скиньте его

**Comment by DedLovesFrogs** [comment]
https://github.com/DedLovesFrogs/Simple-jewelery-DB-app-RU-/blob/main/jewelery_store/jewelery_store/.Designer.cs

Не подгрузился, почему-то, когда закидывал все файлы.
